server:
  port: 8084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guli_oms
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
  rabbitmq:
    host: 192.168.249.201
    virtual-host: /zcg924
    username: zcg924
    password: zcg924
mybatis-plus:
  mapper-locations: classpath:mapper/oms/**/*.xml
  global-config:
    db-config:
      id-type: auto